services:
  all-in-one:
    build:
      context: ./../../
      dockerfile: Dockerfile.all-in-one
    image: urban-events:v1
    container_name: all-in-one
    ports:
      - "80:80" # Maps the host's port 80 to the container's port 80 for Nginx.
      - "5432:5432" # Exposes the internal PostgreSQL port.
      - "6379:6379" # Exposes the internal Redis port.
    environment:
      # Azure Storage Configuration
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER=${AZURE_STORAGE_CONTAINER}
      - AZURE_STORAGE_URL=${AZURE_STORAGE_URL}

      # Application-specific environment variables
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
      - VITE_API_URL_CLIENT=${VITE_API_URL_CLIENT}
      - VITE_API_URL_SERVER=${VITE_API_URL_SERVER}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - APP_KEY=${APP_KEY}
      - APP_CDN_URL=${APP_CDN_URL}
      - APP_FRONTEND_URL=${APP_FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - APP_DISABLE_REGISTRATION=${APP_DISABLE_REGISTRATION}
      - APP_SAAS_MODE_ENABLED=${APP_SAAS_MODE_ENABLED}
      - APP_SAAS_STRIPE_APPLICATION_FEE_PERCENT=${APP_SAAS_STRIPE_APPLICATION_FEE_PERCENT}
      - APP_SAAS_STRIPE_APPLICATION_FEE_FIXED=${APP_SAAS_STRIPE_APPLICATION_FEE_FIXED}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_DRIVER=${MAIL_DRIVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - FILESYSTEM_PUBLIC_DISK=azure
      - FILESYSTEM_PRIVATE_DISK=azure
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - WEBHOOK_QUEUE_NAME=webhook-queue
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_LOG_QUERIES=${APP_LOG_QUERIES}
      - APP_URL=${APP_URL}
      - APP_PORT=${APP_PORT}
      - APP_HOMEPAGE_VIEWS_UPDATE_BATCH_SIZE=${APP_HOMEPAGE_VIEWS_UPDATE_BATCH_SIZE}
      - APP_STRIPE_CONNECT_ACCOUNT_TYPE=${APP_STRIPE_CONNECT_ACCOUNT_TYPE}
      - APP_PLATFORM_SUPPORT_EMAIL=${APP_PLATFORM_SUPPORT_EMAIL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      
      # Database and Cache configuration for internal services
      - DB_CONNECTION=pgsql
      - DB_HOST=localhost # Services are in the same container
      - DB_PORT=5432
      - DB_DATABASE=hi-events
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - REDIS_HOST=localhost # Services are in the same container
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_URL=redis://localhost:6379
