events {}

http {
    server {
        listen 80;
        listen [::]:80;
        server_name _;
        charset utf-8;

        access_log /dev/stdout;
        error_log /dev/stderr;

        # The root for the entire server points to the backend
        root /app/backend/public;

        # All requests for /api are handled by PHP-FPM
        location /api {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # The rest of the requests are routed to the React frontend
        location / {
            # Check if the requested file exists
            root /app/frontend/dist/client; # <-- Corrected path
            try_files $uri $uri/ /index.html;
        }

        # This block executes the PHP script for the backend
        location ~ \.php$ {
            # This is a good practice to ensure requests are routed to the public directory
            root /app/backend/public; 
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # Deny access to hidden files
        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
